radius fixes

diff --git a/init-data-radius b/init-data-radius
--- a/init-data-radius
+++ b/init-data-radius
@@ -25,7 +25,7 @@ test -z "$DEBUG_TRACE" || set -x
 cd /
 
 case "$1" in
-	/bin/bash|bash)
+	/bin/install.sh|/bin/uninstall.sh|/bin/bash|bash)
 		exec "$@"
 	;;
 esac
@@ -75,19 +75,134 @@ fi
 # Debugging:  Turn on tracing of ipa-server-configure-first script
 test -z "$DEBUG_TRACE" || touch /run/ipa/debug-trace
 
+DATA=/data
+COMMAND=
+if [ -n "$1" ] ; then
+	case "$1" in
+		ipa-server-install)
+			COMMAND="$1"
+			shift
+		;;
+		ipa-replica-install)
+			COMMAND="$1"
+			shift
+		;;
+		-*)
+			:
+		;;
+		*)
+		echo "Invocation error: command [$1] not supported." >&2
+		exit 8
 
-#ip route add 10.1.8.0/22 via 192.168.1.1  
+	esac
+fi
+if [ -z "$COMMAND" ] ; then
+	if [ -f $DATA/ipa-replica-install-options ] ; then
+		COMMAND=ipa-replica-install
+	else
+		COMMAND=ipa-server-install
+	fi
+fi
+
+if [ -n "$IPA_SERVER_INSTALL_OPTS" -a "$COMMAND" != 'ipa-server-install' -a "$COMMAND" != 'ipa-replica-install' ] ; then
+	echo "Invocation error: IPA_SERVER_INSTALL_OPTS should only be used with ipa-server-install or ipa-replica-install." >&2
+	exit 7
+fi
+
+OPTIONS_FILE=/run/ipa/$COMMAND-options
+
+DATA_OPTIONS_FILE=$DATA/$COMMAND-options
+touch $OPTIONS_FILE
+chmod 600 $OPTIONS_FILE
+for i in "$@" ; do
+	printf '%q\n' "$i" >> $OPTIONS_FILE
+done
+
+_HOSTNAME_IN_NEXT=false
+for i in $( cat $OPTIONS_FILE ) ; do
+	if $_HOSTNAME_IN_NEXT ; then
+		IPA_SERVER_HOSTNAME="$i"
+		break
+	fi
+        case "$i" in
+                --hostname)
+			_HOSTNAME_IN_NEXT=true
+                        ;;
+                --hostname=*)
+                        IPA_SERVER_HOSTNAME="${i#--hostname=}"
+                        break
+                        ;;
+	esac
+done
+
+if [ -f "$DATA/hostname" ] ; then
+	STORED_HOSTNAME="$( cat $DATA/hostname )"
+	if ! [ "$HOSTNAME" == "$STORED_HOSTNAME" ] ; then
+		# Attempt to set hostname from within container, this
+		# will pass if the container has SYS_ADMIN capability.
+		if hostname $STORED_HOSTNAME 2> /dev/null ; then
+			HOSTNAME=$( hostname )
+			if [ "$HOSTNAME" == "$STORED_HOSTNAME" ] && ! [ "$IPA_SERVER_HOSTNAME" == "$HOSTNAME" ] ; then
+				echo "Using stored hostname $STORED_HOSTNAME, ignoring $IPA_SERVER_HOSTNAME."
+			fi
+		fi
+	fi
+	IPA_SERVER_HOSTNAME=$STORED_HOSTNAME
+fi
+
+HOSTNAME_SHORT=${HOSTNAME%%.*}
+if [ "$HOSTNAME_SHORT" == "$HOSTNAME" ] ; then
+	if [ -z "$IPA_SERVER_HOSTNAME" ] ; then
+		echo "Container invoked without fully-qualified hostname" >&2
+		echo "   and without specifying hostname to use." >&2
+		echo "Consider using -h FQDN option to docker run." >&2
+		exit 15
+	fi
+	# Container is run without FQDN set, we try to "set" it in /etc/hosts
+	cp /etc/hosts /etc/hosts.dist
+	sed "s/$HOSTNAME/$IPA_SERVER_HOSTNAME $IPA_SERVER_HOSTNAME. &/" /etc/hosts.dist > /etc/hosts
+	rm -f /etc/hosts.dist
+	HOSTNAME=$IPA_SERVER_HOSTNAME
+fi
+
+if ! [ -f "$DATA/hostname" ] ; then
+	echo "$HOSTNAME" > "$DATA/hostname"
+fi
+
+DATA_TEMPLATE=/data-template
+
+if ! [ -f /etc/ipa/ca.crt ] ; then
+	if ! [ -f $DATA/ipa.csr ] ; then
+		# Do not refresh $DATA in the second stage of the external CA setup
+		/usr/local/bin/populate-volume-from-template /data
+	fi
+fi
+
+if [ -f "$DATA/build-id" ] ; then
+	if ! cmp -s $DATA/build-id $DATA_TEMPLATE/build-id ; then
+		echo "FreeIPA server is already configured but with different version, volume update."
+		/usr/local/bin/populate-volume-from-template /data
+		sha256sum -c /etc/volume-data-autoupdate 2> /dev/null | awk -F': ' '/OK$/ { print $1 }' \
+			| while read f ; do
+				rm -f "$DATA/$f"
+				if [ -e "$DATA_TEMPLATE/$f" ] ; then
+					( cd $DATA_TEMPLATE && tar cf - "./$f" ) | ( cd $DATA && tar xvf - )
+				fi
+			done
+		cat /etc/volume-data-list | while read i ; do
+			if [ -e $DATA_TEMPLATE$i -a -e $DATA$i ] ; then
+				chown --reference=$DATA_TEMPLATE$i $DATA$i
+				chmod --reference=$DATA_TEMPLATE$i $DATA$i
+			fi
+		done
+		SYSTEMD_OPTS=--unit=ipa-server-upgrade.service
+	fi
+fi
+
+
 
 /usr/local/bin/startup.sh
 
-#mkdir -p -m 755 /var/run/munge
-#mkdir -p -m 700 /var/log/munge
-#chown munge /var/run/munge /var/log/munge
-#chgrp munge /var/run/munge /var/log/munge
-#/sbin/sshd
-#/sbin/munged -f
-#/sbin/crond  
-#/usr/libexec/postfix/master -w
 
 exec /usr/sbin/init --show-status=false $SYSTEMD_OPTS
 
